import { StyleSheet, Dimensions } from 'react-native';

const { width: SW } = Dimensions.get('window');
export const BIG_W = SW * 0.72;
export const BIG_H = 200;
export const SMALL_W = SW * 0.42;

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#fff' },
  safeArea: { flex: 1 },
  scroll: { paddingBottom: 100 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 12,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: 20, fontWeight: '800' },
  greetingBlock: { flex: 1 },
  greetingText: { fontSize: 18, fontWeight: '800', color: '#1e293b' },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 3 },
  locationText: { fontSize: 12, color: '#64748b', fontWeight: '500' },
  locationPlaceholder: { color: '#E8601A', fontWeight: '600' },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 28,
    paddingBottom: 40,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#1e293b', marginBottom: 6 },
  modalSub: { fontSize: 13, color: '#64748b', marginBottom: 20 },
  modalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 20,
  },
  modalInput: { flex: 1, fontSize: 15, color: '#1e293b' },
  modalBtns: { flexDirection: 'row', gap: 12 },
  modalCancelBtn: {
    flex: 1,
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  modalCancelText: { color: '#64748b', fontWeight: '700', fontSize: 15 },
  modalSaveBtn: {
    flex: 1,
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#E8601A',
  },
  modalSaveBtnDisabled: { opacity: 0.45 },
  modalSaveText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  notifBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1.5,
    borderColor: '#fff',
  },

  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginHorizontal: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 20,
  },
  searchIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  searchInput: { flex: 1, fontSize: 14, color: '#1e293b' },

  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1e293b',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  hList: { paddingHorizontal: 16, gap: 12, paddingBottom: 4 },

  bigCard: { borderRadius: 18, overflow: 'hidden' },
  bigCardGradient: { flex: 1, justifyContent: 'flex-end' },
  bigCardDecor: {
    position: 'absolute',
    right: -30,
    top: -30,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  bigCardEmoji: {
    position: 'absolute',
    top: '50%',
    alignSelf: 'center',
    fontSize: 56,
    marginTop: -40,
  },
  bigCardOverlay: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 12,
    margin: 10,
    padding: 10,
  },
  bigCardName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1e293b',
    letterSpacing: 0.2,
  },
  bigCardLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 2,
  },
  bigCardLocationText: { fontSize: 11, color: '#64748b' },

  smallCard: {
    borderRadius: 16,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 1,
    marginBottom: 15,
  },
  smallCardTop: {
    height: SMALL_W * 0.85,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
  },
  smallCardEmoji: { fontSize: 44 },
  smallCardBody: { padding: 10 },
  smallCardName: {
    fontSize: 11,
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: 4,
  },
  smallCardRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 2 },
  smallCardMeta: { fontSize: 10, color: '#94a3b8', flex: 1 },
  vediAltroBtn: {
    backgroundColor: '#E8601A',
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  vediAltroText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
});

export const hStyles = StyleSheet.create({
  orgList: {
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 4,
  },
  orgCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    paddingVertical: 14,
    paddingRight: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
    gap: 12,
  },
  orgCardAccent: {
    width: 4,
    alignSelf: 'stretch',
    backgroundColor: '#E8601A',
    borderRadius: 2,
  },
  orgCardEmoji: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff7ed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orgCardName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 3,
  },
  orgCardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  orgCardMetaText: {
    fontSize: 11,
    color: '#94a3b8',
  },
  orgCardBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  orgTeamsText: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
  },
});
