import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  map: { flex: 1 },
  loadingRoot: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: { fontSize: 14, color: colors.placeholder },

  badge: {
    position: "absolute",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    maxWidth: "85%",
  },
  badgeText: { fontSize: 13, fontWeight: "700", color: colors.dark, flex: 1 },
  badgeDivider: { width: 1, height: 14, backgroundColor: colors.disabled },
  badgeRadius: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primaryGradientMid,
  },

  centerPin: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primaryGradientMid,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primaryGradientMid,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 6,
    borderWidth: 2.5,
    borderColor: colors.white,
  },

  recenterBtn: {
    position: "absolute",
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },

  pin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: colors.primaryGradientMid,
  },
  pinSelected: {
    backgroundColor: colors.white,
    borderColor: colors.danger,
    transform: [{ scale: 1.2 }],
  },
  pinEmoji: { fontSize: 18 },

  tournamentCard: {
    position: "absolute",
    left: 16,
    right: 16,
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    paddingBottom: 0,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 10,
  },
  tournamentCardDismiss: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  tournamentCardName: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.dark,
    marginBottom: 8,
    paddingRight: 24,
    lineHeight: 20,
  },
  tournamentCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  tournamentCardGame: {
    fontSize: 12,
    color: colors.primaryGradientMid,
    fontWeight: "600",
  },
  tournamentCardMeta: { fontSize: 12, color: colors.placeholder },
  tournamentCardDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: colors.grayDark,
  },
  toast: {
    position: "absolute",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.dark,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    maxWidth: "85%",
  },
  toastText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 1,
  },

  modalOverlay: { flex: 1 },
  modalDismiss: { flex: 1 },
  modalCard: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  dragZone: {
    paddingBottom: 4,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.grayDark,
    alignSelf: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.dark,
    marginBottom: 20,
  },
  modalLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.placeholder,
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: "uppercase" as const,
  },
  modalInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.disabled,
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 50,
    marginBottom: 24,
  },
  modalInput: { flex: 1, fontSize: 15, color: colors.dark, paddingVertical: 0 },
  radiusRow: { flexDirection: "row", gap: 10, marginBottom: 28 },
});
