import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  map: { flex: 1 },
  loadingRoot: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: { fontSize: 14, color: "#94a3b8" },

  badge: {
    position: "absolute",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    maxWidth: "85%",
  },
  badgeText: { fontSize: 13, fontWeight: "700", color: "#1e293b", flex: 1 },
  badgeDivider: { width: 1, height: 14, backgroundColor: "#e2e8f0" },
  badgeRadius: { fontSize: 12, fontWeight: "700", color: "#E8601A" },

  centerPin: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#E8601A",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#E8601A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 6,
    borderWidth: 2.5,
    borderColor: "#fff",
  },

  recenterBtn: {
    position: "absolute",
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },

  pin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: "#E8601A",
  },
  pinSelected: {
    backgroundColor: "#FFF0E6",
    borderColor: "#C44E0A",
    transform: [{ scale: 1.2 }],
  },
  pinEmoji: { fontSize: 18 },

  tournamentCard: {
    position: "absolute",
    left: 16,
    right: 16,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    paddingBottom: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 10,
  },
  tournamentCardDismiss: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  tournamentCardName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: 8,
    paddingRight: 24,
    lineHeight: 20,
  },
  tournamentCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  tournamentCardGame: { fontSize: 12, color: "#E8601A", fontWeight: "600" },
  tournamentCardMeta: { fontSize: 12, color: "#64748b" },
  tournamentCardDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#cbd5e1",
  },
  tournamentCardBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#E8601A",
    borderRadius: 50,
    paddingVertical: 12,
  },
  tournamentCardBtnText: { color: "#fff", fontSize: 14, fontWeight: "800" },

  toast: {
    position: "absolute",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#1e293b",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    maxWidth: "85%",
  },
  toastText: { color: "#fff", fontSize: 13, fontWeight: "600", flexShrink: 1 },

  modalOverlay: { flex: 1 },
  modalDismiss: { flex: 1 },
  modalCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  dragZone: {
    paddingBottom: 4,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#e2e8f0",
    alignSelf: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: 20,
  },
  modalLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94a3b8",
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: "uppercase" as const,
  },
  modalInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 24,
  },
  modalInput: { flex: 1, fontSize: 15, color: "#1e293b" },
  radiusRow: { flexDirection: "row", gap: 10, marginBottom: 28 },
  radiusBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
  },
  radiusBtnActive: { borderColor: "#E8601A", backgroundColor: "#FFF0E6" },
  radiusBtnText: { fontSize: 13, fontWeight: "700", color: "#64748b" },
  radiusBtnTextActive: { color: "#E8601A" },
  applyBtn: {
    backgroundColor: "#E8601A",
    borderRadius: 50,
    paddingVertical: 16,
    alignItems: "center",
  },
  applyBtnText: { color: "#fff", fontSize: 16, fontWeight: "800" },
});
