import { StyleSheet } from 'react-native';

export const tss = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f8fafc' },
  centerBox: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  backBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: '800', color: '#1e293b', paddingLeft: 4 },
  addBtn: {},
  addBtnGrad: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  scrollContent: { padding: 16, gap: 12 },

  teamCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  teamAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamAvatarText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  teamName: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  teamMeta: { fontSize: 12, color: '#64748b', marginTop: 2 },
  teamRep: { fontSize: 11, color: '#94a3b8', marginTop: 2 },

  emptyBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  emptyIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#94a3b8' },
  emptySub: { fontSize: 13, color: '#cbd5e1', textAlign: 'center', marginTop: 8, lineHeight: 20 },
  createBtn: {
    marginTop: 24,
    backgroundColor: '#E8601A',
    borderRadius: 50,
    paddingVertical: 14,
    paddingHorizontal: 40,
  },
  createBtnText: { color: '#fff', fontSize: 15, fontWeight: '800' },

  invitesSection: {
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    marginBottom: 4,
  },
  invitesSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  inviteCard: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f8fafc',
  },
  inviteCardAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inviteCardAvatarText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  inviteCardInfo: { flex: 1 },
  inviteTeamName: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  inviteCardFrom: { fontSize: 12, color: '#94a3b8', marginTop: 2 },
  inviteCardActions: {
    flexDirection: 'row',
    gap: 10,
  },
  inviteAcceptBtn: {
    flex: 1,
    backgroundColor: '#10b981',
    borderRadius: 50,
    paddingVertical: 10,
    alignItems: 'center',
  },
  inviteAcceptText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  inviteRejectBtn: {
    flex: 1,
    borderRadius: 50,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#ef4444',
  },
  inviteRejectText: { color: '#ef4444', fontSize: 13, fontWeight: '700' },
});
