import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const tds = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  centerBox: { flex: 1, alignItems: "center", justifyContent: "center" },

  header: { paddingBottom: 28 },
  headerTop: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  menuOverlay: {
    flex: 1,
  },
  menuCard: {
    position: "absolute",
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingVertical: 6,
    minWidth: 180,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 13,
    paddingHorizontal: 16,
  },
  menuItemDanger: {
    borderTopWidth: 1,
    borderTopColor: colors.gray,
  },
  menuItemText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.dark,
  },
  headerBody: { alignItems: "center", paddingBottom: 8 },
  teamAvatarLarge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.grayOpacized,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 3,
    borderColor: colors.grayOpacized,
  },
  teamAvatarLargeText: { color: colors.white, fontSize: 28, fontWeight: "900" },
  teamAvatarImage: { width: 72, height: 72, borderRadius: 36 },
  teamName: {
    color: colors.white,
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  sportChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.opacized,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 8,
  },
  sportChipText: { color: colors.white, fontSize: 12, fontWeight: "600" },
  membersCount: { color: colors.grayOpacized, fontSize: 12, marginTop: 6 },

  // ── Sport select (edit mode) ───────────────────────────────────
  sportSelectBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.5)",
  },
  sportSelectText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.white,
  },

  // ── Inline edit mode ───────────────────────────────────────────
  saveBtn: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "700",
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  teamNameInput: {
    color: colors.white,
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    borderBottomWidth: 1.5,
    borderBottomColor: "rgba(255,255,255,0.5)",
    paddingVertical: 4,
    marginTop: 8,
    marginBottom: 2,
    minWidth: 160,
    maxWidth: 260,
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: 0,
    right: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.9)",
  },

  section: {
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },

  roleOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  roleOptionCurrent: {},
  roleOptionDisabled: { opacity: 0.4 },
  roleOptionText: {
    fontSize: 15,
    color: colors.placeholder,
    fontWeight: "500",
  },
  roleOptionTextCurrent: {
    color: colors.primaryGradientMid,
    fontWeight: "700",
  },
  roleOptionTextDisabled: {},

  pendingInviteRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    gap: 12,
  },
  pendingInviteAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
  },
  pendingInviteAvatarText: { fontSize: 18, color: colors.placeholder },
  pendingInviteName: { fontSize: 13, fontWeight: "600", color: colors.dark },
  pendingInviteSub: { fontSize: 11, color: colors.placeholder, marginTop: 1 },
  pendingBadge: {
    backgroundColor: colors.yellow,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pendingBadgeText: { fontSize: 11, color: colors.brown, fontWeight: "700" },
  inviteBadgeAccepted: {
    backgroundColor: "#d1fae5",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  inviteBadgeTextAccepted: { fontSize: 11, color: colors.success, fontWeight: "700" },
  inviteBadgeDeclined: {
    backgroundColor: colors.gray,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  inviteBadgeTextDeclined: { fontSize: 11, color: colors.placeholder, fontWeight: "700" },

  jerseyBadge: {
    minWidth: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  jerseyBadgeEditable: {
    backgroundColor: colors.primarySelectedBg,
  },
  jerseyText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.placeholder,
  },
  jerseyTextEditable: {
    color: colors.primary,
  },
  jerseyEmpty: {
    fontSize: 18,
    color: colors.primaryGradientMid,
    lineHeight: 22,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: colors.opacized,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  modalCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    width: "100%",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  modalAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primarySelectedBg,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: colors.primaryGradientMidOpacized,
  },
  modalAvatarText: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.danger,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
    marginBottom: 10,
  },
  modalBody: {
    fontSize: 14,
    color: colors.placeholder,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 6,
  },
  modalMemberName: {
    fontWeight: "700",
    color: colors.dark,
  },
  logoPickerContainer: {
    position: "relative",
    marginBottom: 16,
  },
  logoPickerImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  logoPickerPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primarySelectedBg,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.primaryGradientMidOpacized,
    borderStyle: "dashed",
  },
  logoPickerInitials: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.primary,
  },
  logoPickerBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  editNameInput: {
    width: "100%",
    borderWidth: 1.5,
    borderColor: colors.primarySelectedBg,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    fontWeight: "700",
    color: colors.dark,
    marginBottom: 20,
  },
  // ── Tab bar ────────────────────────────────────────────────────
  tabBar: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginTop: 14,
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 9,
    alignItems: "center",
  },
  tabBtnActive: {
    backgroundColor: colors.primary,
  },
  tabBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.placeholder,
  },
  tabBtnTextActive: {
    color: colors.white,
  },

  // ── Stats card (Statistiche tab) ───────────────────────────────
  statsCard: {
    marginHorizontal: 16,
    borderRadius: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  statsCardInner: {
    backgroundColor: colors.white,
    borderRadius: 16,
    overflow: "hidden",
  },
  statsRow: {
    flexDirection: "row",
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  statBubble: {
    flex: 1,
    alignItems: "center",
  },
  statNum: {
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 32,
  },
  statLabel: {
    fontSize: 11,
    color: colors.placeholder,
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  statDivider: {
    width: 1,
    backgroundColor: colors.gray,
    alignSelf: "stretch",
  },
  statsTourneyRow: {
    flexDirection: "row",
    paddingVertical: 14,
  },
  statTourney: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  statTourneyNum: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
  },
  statTourneyLabel: {
    fontSize: 10,
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  statTourneyDivider: {
    width: 1,
    backgroundColor: colors.gray,
    alignSelf: "stretch",
  },
  cardIndicatorYellow: {
    width: 16,
    height: 20,
    borderRadius: 3,
    backgroundColor: colors.primaryGradientEnd,
  },
  cardIndicatorRed: {
    width: 16,
    height: 20,
    borderRadius: 3,
    backgroundColor: colors.danger,
  },

  // ── Goal scorers (Classifica tab) ──────────────────────────────
  scorerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    gap: 10,
  },
  scorerRankBox: {
    width: 24,
    alignItems: "center",
  },
  scorerRank: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.grayDark,
  },
  scorerAvatar: {},
  scorerAvatarGradient: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  scorerAvatarText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "800",
  },
  scorerName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: colors.dark,
  },
  scorerGoalsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primarySelectedBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  scorerGoals: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.primary,
  },

  // ── Tournament accordion (Tornei tab) ──────────────────────────
  tournamentAccordion: {
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  tournamentAccordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
  },
  tournamentAccordionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
  },
  tournamentAccordionIconText: {
    fontSize: 18,
  },
  tournamentAccordionName: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.dark,
    marginBottom: 2,
  },
  tournamentAccordionMeta: {
    fontSize: 11,
    color: colors.placeholder,
  },
  tournamentBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 20,
  },
  tournamentBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.dark,
  },
  tournamentScorers: {
    borderTopWidth: 1,
    borderTopColor: colors.gray,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  tournamentScorerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  tournamentScorerName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: colors.dark,
  },
  tournamentScorerGoals: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primary,
  },

  // ── Empty state ────────────────────────────────────────────────
  emptyText: {
    fontSize: 13,
    color: colors.placeholder,
    textAlign: "center",
    paddingVertical: 24,
    paddingHorizontal: 16,
  },

  modalWarning: {
    fontSize: 12,
    color: colors.placeholder,
    marginBottom: 24,
    textAlign: "center",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  modalCancelBtn: {
    flex: 1,
    backgroundColor: colors.gray,
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: "center",
  },
  modalRemoveBtn: {
    flex: 1,
    backgroundColor: colors.danger,
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: "center",
  },
});
