import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const tds = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f8fafc" },
  centerBox: { flex: 1, alignItems: "center", justifyContent: "center" },

  header: { paddingBottom: 28 },
  headerTop: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerBody: { alignItems: "center", paddingBottom: 8 },
  teamAvatarLarge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.5)",
  },
  teamAvatarLargeText: { color: "#fff", fontSize: 28, fontWeight: "900" },
  teamName: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  sportChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0,0,0,0.18)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 8,
  },
  sportChipText: { color: "#fff", fontSize: 12, fontWeight: "600" },
  membersCount: { color: "rgba(255,255,255,0.8)", fontSize: 12, marginTop: 6 },

  section: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },

  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f8fafc",
    gap: 12,
  },
  memberRowRep: { backgroundColor: colors.primarySelectedBg },
  memberAvatar: {},
  memberAvatarRep: {},
  memberAvatarInner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAvatarText: { color: "#fff", fontSize: 16, fontWeight: "800" },
  memberNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  memberName: { fontSize: 14, fontWeight: "700", color: "#1e293b" },
  crownBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    backgroundColor: "#FFF0E6",
    borderRadius: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  crownText: { fontSize: 10, color: "#E8601A", fontWeight: "700" },
  memberUsername: { fontSize: 12, color: "#94a3b8", marginTop: 1 },
  memberRole: { fontSize: 11, color: "#cbd5e1", fontWeight: "600" },

  rolePillStatic: {
    backgroundColor: "#f8fafc",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  rolePillText: { fontSize: 10, color: "#64748b", fontWeight: "600" },

  roleOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  roleOptionCurrent: {},
  roleOptionDisabled: { opacity: 0.4 },
  roleOptionText: { fontSize: 15, color: "#1e293b", fontWeight: "500" },
  roleOptionTextCurrent: { color: "#E8601A", fontWeight: "700" },
  roleOptionTextDisabled: {},

  pendingInviteRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f8fafc",
    gap: 12,
  },
  pendingInviteAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  pendingInviteAvatarText: { fontSize: 18, color: "#94a3b8" },
  pendingInviteName: { fontSize: 13, fontWeight: "600", color: "#1e293b" },
  pendingInviteSub: { fontSize: 11, color: "#94a3b8", marginTop: 1 },
  pendingBadge: {
    backgroundColor: "#fef9c3",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pendingBadgeText: { fontSize: 11, color: "#854d0e", fontWeight: "700" },

  inviteBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingVertical: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: "#fed7aa",
  },
  inviteBtnText: { color: "#E8601A", fontSize: 15, fontWeight: "700" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  modalAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fef2f2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#fecaca",
  },
  modalAvatarText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ef4444",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: 10,
  },
  modalBody: {
    fontSize: 14,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 6,
  },
  modalMemberName: {
    fontWeight: "700",
    color: "#1e293b",
  },
  modalWarning: {
    fontSize: 12,
    color: "#94a3b8",
    marginBottom: 24,
    textAlign: "center",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  modalCancelBtn: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#64748b",
  },
  modalRemoveBtn: {
    flex: 1,
    backgroundColor: "#ef4444",
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: "center",
  },
  modalRemoveText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff",
  },
});
