import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const tss = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  centerBox: { flex: 1, alignItems: "center", justifyContent: "center" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
    paddingLeft: 4,
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },

  scrollContent: { padding: 16, gap: 12 },

  teamCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  teamAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  teamAvatarText: { color: colors.white, fontSize: 18, fontWeight: "800" },
  teamName: { fontSize: 15, fontWeight: "700", color: colors.dark },
  teamMeta: { fontSize: 12, color: colors.placeholder, marginTop: 2 },
  teamRep: { fontSize: 11, color: colors.grayDark, marginTop: 2 },

  emptyBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: { fontSize: 18, fontWeight: "700", color: colors.grayDark },
  emptySub: {
    fontSize: 13,
    color: colors.grayDark,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
  },
  createBtn: {
    marginTop: 24,
    backgroundColor: colors.primaryGradientMid,
    borderRadius: 50,
    paddingVertical: 14,
    paddingHorizontal: 40,
  },
  createBtnText: { color: colors.white, fontSize: 15, fontWeight: "800" },

  invitesSection: {
    backgroundColor: colors.white,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    marginBottom: 4,
  },
  invitesSectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.grayDark,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  inviteCard: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  inviteCardAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  inviteCardAvatarText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  inviteCardInfo: { flex: 1 },
  inviteTeamName: { fontSize: 15, fontWeight: "700", color: colors.dark },
  inviteCardFrom: { fontSize: 12, color: colors.grayDark, marginTop: 2 },
  inviteCardActions: {
    flexDirection: "row",
    gap: 10,
  },
});
