import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const cd = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  headerInfo: { flex: 1 },
  headerName: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.dark,
  },
  headerSub: {
    fontSize: 12,
    color: colors.placeholder,
    marginTop: 1,
  },
  messageList: { flex: 1, paddingHorizontal: 16 },
  messageListContent: { paddingVertical: 16, gap: 10 },
  bubbleWrap: { flexDirection: "row" },
  bubbleWrapMe: { flexDirection: "row", justifyContent: "flex-end" },
  bubble: {
    maxWidth: "75%",
    backgroundColor: colors.white,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  bubbleMe: {
    maxWidth: "75%",
    backgroundColor: colors.primary,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bubbleText: { fontSize: 14, color: colors.dark, lineHeight: 20 },
  bubbleTextMe: { fontSize: 14, color: colors.white, lineHeight: 20 },
  bubbleTime: {
    fontSize: 10,
    color: colors.grayDark,
    marginTop: 4,
    textAlign: "right",
  },
  bubbleTimeMe: {
    fontSize: 10,
    color: "rgba(255,255,255,0.7)",
    marginTop: 4,
    textAlign: "right",
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: colors.gray,
  },
  textInput: {
    flex: 1,
    backgroundColor: colors.gray,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.dark,
    maxHeight: 120,
    minHeight: 42,
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  sendBtnDisabled: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.gray,
    justifyContent: "center",
    alignItems: "center",
  },
  dateDivider: {
    alignItems: "center",
    marginVertical: 8,
  },
  dateDividerText: {
    fontSize: 12,
    color: colors.grayDark,
    backgroundColor: colors.gray,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 10,
  },
});
