import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const r = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
    textAlign: "center",
  },
  headerSide: { width: 36 },

  // Tab bar
  tabBar: {
    flexDirection: "row",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: colors.primary },
  tabText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tabTextActive: { color: colors.primary },

  // Scroll
  scroll: { paddingBottom: 32 },

  // Date group header (Calendario tab)
  dateHeader: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 6,
  },
  dateHeaderText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.dark,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Match card (Calendario tab)
  matchCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: colors.white,
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  matchCardAccent: {
    width: 4,
    alignSelf: "stretch",
  },
  matchCardInner: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
  },
  matchTime: { fontSize: 13, fontWeight: "800", color: colors.dark, width: 42 },
  matchField: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.placeholder,
    textTransform: "uppercase",
  },
  matchTeams: { flex: 1 },
  matchTeamRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  matchTeamName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: colors.dark,
  },
  matchVs: {
    fontSize: 10,
    color: colors.placeholder,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 1,
  },
  matchLabel: {
    backgroundColor: colors.gray,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  matchLabelText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.placeholder,
  },
  matchLabelFinal: { backgroundColor: colors.primarySelectedBg },
  matchLabelFinalText: { color: colors.primary },
  matchByeBadge: {
    backgroundColor: colors.gray,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  matchByeText: { fontSize: 10, color: colors.placeholder, fontWeight: "600" },

  // Team schedule card
  teamPickerRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  teamChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.gray,
    borderWidth: 1.5,
    borderColor: colors.disabled,
  },
  teamChipSelected: {
    backgroundColor: colors.primarySelectedBg,
    borderColor: colors.primary,
  },
  teamChipText: { fontSize: 12, fontWeight: "700", color: colors.placeholder },
  teamChipTextSelected: { color: colors.primary },

  teamMatchRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 12,
    padding: 14,
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  teamMatchRoundBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
  },
  teamMatchRoundText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.placeholder,
    textAlign: "center",
  },
  teamMatchInfo: { flex: 1 },
  teamMatchOpponent: { fontSize: 14, fontWeight: "700", color: colors.dark },
  teamMatchMeta: { fontSize: 11, color: colors.placeholder, marginTop: 2 },
  teamMatchField: {
    alignItems: "center",
    backgroundColor: colors.gray,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  teamMatchFieldText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.placeholder,
  },

  // Referee sheet card
  refCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.disabled,
  },
  refCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  refCardTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  refCardMeta: { fontSize: 11, color: colors.grayDark },
  refTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  refTeamName: { flex: 1, fontSize: 15, fontWeight: "700", color: colors.dark },
  refScoreBox: {
    width: 48,
    height: 40,
    borderWidth: 1.5,
    borderColor: colors.disabled,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  refScoreText: { fontSize: 18, fontWeight: "800", color: colors.dark },
  refDivider: { height: 1, backgroundColor: colors.gray, marginVertical: 4 },
  refVs: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: "700",
    color: colors.placeholder,
    paddingVertical: 2,
  },
  refFieldBadge: {
    backgroundColor: colors.primarySelectedBg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  refFieldText: { fontSize: 11, fontWeight: "700", color: colors.primary },

  // Standings table
  standingsCard: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: colors.white,
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  standingsHeader: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.gray,
  },
  standingsHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.placeholder,
    textTransform: "uppercase",
    textAlign: "center",
  },
  standingsRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    alignItems: "center",
  },
  standingsRowEven: { backgroundColor: "#fafbfc" },
  standingsPos: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.placeholder,
    width: 24,
    textAlign: "center",
  },
  standingsName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: colors.dark,
    paddingLeft: 8,
  },
  standingsCell: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.dark,
    textAlign: "center",
  },
  standingsPts: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.primary,
    textAlign: "center",
  },

  emptyState: {
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 32,
    gap: 12,
  },
  emptyText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.placeholder,
    textAlign: "center",
  },

  // Sub-tab bar (Struttura tab)
  subTabBar: {
    flexDirection: "row",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    paddingHorizontal: 16,
  },
  subTab: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    marginRight: 8,
  },
  subTabActive: { borderBottomColor: colors.purpleBlue },
  subTabText: { fontSize: 13, fontWeight: "700", color: colors.placeholder },
  subTabTextActive: { color: colors.purpleBlue },

  // Group card (Gironi sub-tab)
  groupCard: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: colors.white,
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  groupCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.purpleBlue,
    gap: 8,
  },
  groupCardTitle: { fontSize: 15, fontWeight: "800", color: colors.white },
  groupCardCount: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.7)",
    marginLeft: "auto",
  },
  groupTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  groupTeamPos: {
    width: 24,
    fontSize: 13,
    fontWeight: "800",
    color: colors.placeholder,
    textAlign: "center",
  },
  groupTeamName: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: colors.dark,
    paddingLeft: 8,
  },

  // Group match section
  groupMatchesSection: {
    borderTopWidth: 1,
    borderTopColor: colors.gray,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  groupRoundLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
    marginBottom: 6,
  },
  groupMatchRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    gap: 6,
  },
  groupMatchTeam: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: colors.dark,
  },
  groupMatchVs: { fontSize: 10, fontWeight: "700", color: colors.placeholder },
});
