import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    gap: 4,
  },
  backBtn: { marginRight: 4, padding: 2 },
  header: { fontSize: 22, fontWeight: "800", color: colors.dark, flex: 1 },
  list: { paddingHorizontal: 16, paddingBottom: 100 },
  separator: { height: 8 },
  item: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    borderRadius: 16,
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  itemUnread: { backgroundColor: colors.primarySelectedBg },
  itemLeft: { paddingTop: 4 },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.danger,
    marginTop: 2,
  },
  dotRead: { backgroundColor: colors.grayDark },
  itemBody: { flex: 1 },
  itemTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.placeholder,
    marginBottom: 3,
  },
  itemTitleUnread: { fontWeight: "800", color: colors.dark },
  itemText: { fontSize: 13, color: colors.placeholder, lineHeight: 19 },
  itemDate: { fontSize: 11, color: colors.grayDark, marginTop: 6 },
  empty: {
    alignItems: "center",
    paddingTop: 80,
    gap: 12,
  },
  emptyText: { fontSize: 15, color: colors.grayDark, fontWeight: "500" },
});
