import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  scroll: { flex: 1 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  errorText: { color: colors.danger, fontSize: 14 },

  header: { paddingBottom: 28 },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  bookmarkBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.opacized,
    alignItems: "center",
    justifyContent: "center",
  },
  statusBadge: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  statusText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  headerContent: { paddingHorizontal: 20, marginBottom: 20 },
  headerGame: {
    color: colors.grayOpacized,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  headerTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  chipsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    flexWrap: "wrap",
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: colors.opacized,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipText: { color: colors.white, fontSize: 12, fontWeight: "600" },

  body: { padding: 16, gap: 12 },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  rowLabel: { flex: 1, fontSize: 13, color: colors.placeholder, marginLeft: 2 },
  rowValue: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.dark,
    maxWidth: "55%" as any,
    textAlign: "right",
  },

  progressBg: {
    height: 8,
    backgroundColor: colors.gray,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.primaryGradientMid,
    borderRadius: 4,
  },
  progressLabels: { flexDirection: "row", justifyContent: "space-between" },
  progressText: { fontSize: 12, color: colors.placeholder },

  description: { fontSize: 14, color: colors.placeholder, lineHeight: 22 },

  ruleItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 10,
  },
  ruleNumber: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primarySelectedBg,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  ruleNumberText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primaryGradientMid,
  },
  ruleText: {
    flex: 1,
    fontSize: 14,
    color: colors.placeholder,
    lineHeight: 20,
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.white,
    paddingHorizontal: 20,
    paddingTop: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
    gap: 16,
  },
  costBlock: {},
  costLabel: {
    fontSize: 11,
    color: colors.placeholder,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  costValue: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.dark,
    marginTop: 2,
  },
  rowValueLink: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.primaryGradientMid,
    maxWidth: "55%" as any,
    textAlign: "right",
    textDecorationLine: "underline",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.darkSemiOpacized,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modalCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 24,
    width: "100%" as any,
    gap: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
  },
  modalBody: {
    fontSize: 14,
    color: colors.placeholder,
    lineHeight: 20,
  },
  modalBtns: {
    flexDirection: "row",
    gap: 10,
  },
  modalBtnCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.disabled,
    alignItems: "center",
  },
  modalBtnOpen: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primaryGradientMid,
    alignItems: "center",
  },
  modalBtnCancelText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.placeholder,
  },
  modalBtnOpenText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.white,
  },
});
