import { StyleSheet } from "react-native";
import { colors } from "../../../../theme/colors";

export const styles = StyleSheet.create({
  card: {
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    paddingVertical: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    display: "flex",
    flexDirection: "row",
    gap: 20,
    paddingHorizontal: 10,
    minHeight: 100,
  },
  cardEdit: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    paddingHorizontal: 0,
    paddingTop: 20,
    paddingBottom: 10,
  },
  avatarWrapper: {
    position: "relative",
  },
  pencilBtn: {
    position: "absolute",
    bottom: 0,
    right: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  username: { fontSize: 18, fontWeight: "800", color: colors.dark },
  email: { fontSize: 13, color: colors.placeholder, marginTop: 4 },
  cardSavingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.opacized,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
});
