import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f8fafc' },
  scroll: { paddingBottom: 32 },
  header: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1e293b',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  card: {
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    paddingVertical: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 12,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImg: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  avatarText: { color: '#fff', fontSize: 28, fontWeight: '800' },
  pencilBtn: {
    position: 'absolute',
    bottom: 0,
    right: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E8601A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  username: { fontSize: 18, fontWeight: '800', color: '#1e293b' },
  email: { fontSize: 13, color: '#64748b', marginTop: 4 },
  section: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 8,
  },
  rowLast: { borderBottomWidth: 0 },
  rowLabel: {
    fontSize: 11,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  rowValue: { fontSize: 14, fontWeight: '600', color: '#1e293b', marginTop: 1 },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: '#fed7aa',
  },
  editBtnText: { color: '#E8601A', fontSize: 15, fontWeight: '700' },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: '#fecaca',
  },
  logoutText: { color: '#ef4444', fontSize: 15, fontWeight: '700' },
  teamsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  teamsTitle: { fontSize: 16, fontWeight: '800', color: '#1e293b' },
  teamsViewAll: { fontSize: 13, color: '#E8601A', fontWeight: '700' },
  teamsScroll: { paddingHorizontal: 16, gap: 10, paddingBottom: 4 },
  teamMiniCard: {
    width: 100,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  teamMiniAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  teamMiniAvatarText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  teamMiniName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1e293b',
    textAlign: 'center',
    lineHeight: 14,
  },
  teamMiniSport: { fontSize: 10, color: '#94a3b8', marginTop: 2 },
  addTeamBtn: { width: 100, alignItems: 'center', justifyContent: 'center' },
  addTeamBtnGrad: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  addTeamBtnText: { fontSize: 11, fontWeight: '700', color: '#E8601A' },
  createTeamCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1.5,
    borderColor: '#fed7aa',
  },
  createTeamIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createTeamTitle: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  createTeamSub: { fontSize: 11, color: '#94a3b8', marginTop: 2 },
  guestBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  guestTitle: { fontSize: 18, fontWeight: '700', color: '#94a3b8', marginTop: 16 },
  guestSub: { fontSize: 13, color: '#cbd5e1', marginTop: 6, textAlign: 'center' },
  loginBtn: {
    marginTop: 24,
    backgroundColor: '#E8601A',
    borderRadius: 50,
    paddingVertical: 14,
    paddingHorizontal: 48,
  },
  loginBtnText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  registerLink: { color: '#E8601A', fontWeight: '600', fontSize: 14 },
});

export const pStyles = StyleSheet.create({
  statsCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  statsRow: {
    flexDirection: 'row',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  statBubble: {
    flex: 1,
    alignItems: 'center',
  },
  statNum: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 32,
  },
  statLabel: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  statDivider: {
    width: 1,
    backgroundColor: '#f1f5f9',
    alignSelf: 'stretch',
  },
  statsTourneyRow: {
    flexDirection: 'row',
    paddingVertical: 14,
  },
  statTourney: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
  },
  statTourneyNum: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1e293b',
  },
  statTourneyLabel: {
    fontSize: 10,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  statTourneyDivider: {
    width: 1,
    backgroundColor: '#f1f5f9',
    alignSelf: 'stretch',
  },
  orgCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    padding: 14,
    gap: 12,
  },
  orgCardLeft: {
    width: 4,
    borderRadius: 2,
    backgroundColor: '#E8601A',
    alignSelf: 'stretch',
  },
  orgCardName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
    flex: 1,
    marginRight: 8,
  },
  orgSportBadge: {
    backgroundColor: '#fff7ed',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  orgSportText: {
    fontSize: 11,
    color: '#E8601A',
    fontWeight: '700',
  },
  orgCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  orgCardMeta: {
    fontSize: 11,
    color: '#94a3b8',
  },
  orgCardMetaDot: {
    fontSize: 11,
    color: '#cbd5e1',
  },
  orgCardStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  orgCardStat: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
  },
});
