import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.gray },
  scroll: { paddingBottom: 32 },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  headerText: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.dark,
  },
  card: {
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    paddingVertical: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    display: "flex",
    flexDirection: "row",
    gap: 20,
    paddingHorizontal: 10,
    minHeight: 100,
  },
  cardSavingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.opacized,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cardEdit: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    paddingHorizontal: 0,
    paddingTop: 20,
    paddingBottom: 10,
  },
  cardEditFields: {
    width: "100%",
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.gray,
  },
  avatarWrapper: {
    position: "relative",
  },
  pencilBtn: {
    position: "absolute",
    bottom: 0,
    right: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  username: { fontSize: 18, fontWeight: "800", color: colors.dark },
  email: { fontSize: 13, color: colors.placeholder, marginTop: 4 },
  teamsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  teamsTitle: { fontSize: 16, fontWeight: "800", color: colors.dark },
  teamsViewAll: {
    fontSize: 13,
    color: colors.primaryGradientMid,
    fontWeight: "700",
  },
  teamsScroll: { paddingHorizontal: 16, gap: 10, paddingBottom: 4 },
  teamMiniCard: {
    width: 100,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  teamMiniAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  teamMiniAvatarText: { color: colors.white, fontSize: 16, fontWeight: "800" },
  teamMiniName: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.dark,
    textAlign: "center",
    lineHeight: 14,
  },
  teamMiniSport: { fontSize: 10, color: colors.placeholder, marginTop: 2 },
  createTeamCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1.5,
    borderColor: colors.primarySelectedBg,
  },
  createTeamIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  createTeamTitle: { fontSize: 14, fontWeight: "700", color: colors.dark },
  createTeamSub: { fontSize: 11, color: colors.placeholder, marginTop: 2 },
});

export const pStyles = StyleSheet.create({
  statsCard: {
    marginHorizontal: 16,
    borderRadius: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  statsCardInner: {
    backgroundColor: colors.white,
    borderRadius: 16,
    overflow: "hidden",
  },
  statsRow: {
    flexDirection: "row",
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  statBubble: {
    flex: 1,
    alignItems: "center",
  },
  statNum: {
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 32,
  },
  statLabel: {
    fontSize: 11,
    color: colors.placeholder,
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  statDivider: {
    width: 1,
    backgroundColor: colors.gray,
    alignSelf: "stretch",
  },
  statsTourneyRow: {
    flexDirection: "row",
    paddingVertical: 14,
  },
  statTourney: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  statTourneyNum: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
  },
  statTourneyLabel: {
    fontSize: 10,
    color: colors.placeholder,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  statTourneyDivider: {
    width: 1,
    backgroundColor: colors.gray,
    alignSelf: "stretch",
  },
});
