import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f8fafc" },
  scroll: { paddingBottom: 32 },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  headerText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1e293b",
  },
  headerTextDone: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.primary,
  },
  card: {
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    display: "flex",
    flexDirection: "row",
    gap: 20,
    paddingHorizontal: 10,
    minHeight: 100,
  },
  cardSavingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cardEdit: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    paddingHorizontal: 0,
    paddingTop: 20,
    paddingBottom: 10,
  },
  cardEditFields: {
    width: "100%",
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  avatarWrapper: {
    position: "relative",
  },
  pencilBtn: {
    position: "absolute",
    bottom: 0,
    right: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  username: { fontSize: 18, fontWeight: "800", color: "#1e293b" },
  email: { fontSize: 13, color: "#64748b", marginTop: 4 },
  section: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    gap: 8,
  },
  rowLast: { borderBottomWidth: 0 },
  rowLabel: {
    fontSize: 11,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  rowValue: { fontSize: 14, fontWeight: "600", color: "#1e293b", marginTop: 1 },
  editActions: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  saveBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  saveBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
  cancelBtn: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  cancelBtnText: { color: "#64748b", fontSize: 14, fontWeight: "600" },
  doneBtn: {
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  doneBtnText: { color: "#fff", fontSize: 15, fontWeight: "700" },
  editBtn: {
    alignSelf: "flex-end",
    borderRadius: 14,
    overflow: "hidden",
    borderColor: colors.primary,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 5,
  },
  editBtnGradient: {},
  editBtnText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "700",
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: "#fecaca",
  },
  logoutText: { color: "#ef4444", fontSize: 15, fontWeight: "700" },
  teamsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  teamsTitle: { fontSize: 16, fontWeight: "800", color: "#1e293b" },
  teamsViewAll: { fontSize: 13, color: "#E8601A", fontWeight: "700" },
  teamsScroll: { paddingHorizontal: 16, gap: 10, paddingBottom: 4 },
  teamMiniCard: {
    width: 100,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  teamMiniAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  teamMiniAvatarText: { color: "#fff", fontSize: 16, fontWeight: "800" },
  teamMiniName: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1e293b",
    textAlign: "center",
    lineHeight: 14,
  },
  teamMiniSport: { fontSize: 10, color: "#94a3b8", marginTop: 2 },
  addTeamBtn: { width: 100, alignItems: "center", justifyContent: "center" },
  addTeamBtnGrad: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  addTeamBtnText: { fontSize: 11, fontWeight: "700", color: "#E8601A" },
  createTeamCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1.5,
    borderColor: "#fed7aa",
  },
  createTeamIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  createTeamTitle: { fontSize: 14, fontWeight: "700", color: "#1e293b" },
  createTeamSub: { fontSize: 11, color: "#94a3b8", marginTop: 2 },
  guestBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  guestTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#94a3b8",
    marginTop: 16,
  },
  guestSub: {
    fontSize: 13,
    color: "#cbd5e1",
    marginTop: 6,
    textAlign: "center",
  },
});

export const pStyles = StyleSheet.create({
  statsCard: {
    marginHorizontal: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  statsCardInner: {
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
  },
  statsRow: {
    flexDirection: "row",
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  statBubble: {
    flex: 1,
    alignItems: "center",
  },
  statNum: {
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 32,
  },
  statLabel: {
    fontSize: 11,
    color: "#94a3b8",
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  statDivider: {
    width: 1,
    backgroundColor: "#f1f5f9",
    alignSelf: "stretch",
  },
  statsTourneyRow: {
    flexDirection: "row",
    paddingVertical: 14,
  },
  statTourney: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  statTourneyNum: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  statTourneyLabel: {
    fontSize: 10,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  statTourneyDivider: {
    width: 1,
    backgroundColor: "#f1f5f9",
    alignSelf: "stretch",
  },
});
