import { StyleSheet } from "react-native";
import { colors } from "../../../theme/colors";

export const oStyles = StyleSheet.create({
  orgBadge: {
    backgroundColor: colors.purpleBlue,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 8,
  },
  orgBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.white,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  orgHeaderCard: {
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    gap: 12,
    display: "flex",
    flexDirection: "row",
  },
  orgOrgName: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.dark,
    textAlign: "center",
  },
  orgSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  orgSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.dark,
  },
  orgHeaderInfo: { display: "flex", flexDirection: "column", gap: 8 },
  orgSectionCount: {
    fontSize: 12,
    color: colors.placeholder,
    fontWeight: "600",
  },
  orgTournamentCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  orgTournamentIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.primarySelectedBg,
    alignItems: "center",
    justifyContent: "center",
  },
  orgTournamentInfo: {
    flex: 1,
  },
  orgTournamentName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.dark,
    marginBottom: 4,
  },
  orgTournamentMeta: {
    fontSize: 11,
    color: colors.placeholder,
  },
  orgTournamentChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 8,
  },
  orgTournamentChipText: {
    fontSize: 10,
    fontWeight: "600",
    color: colors.white,
  },
  collaboratorRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginVertical: 10,
    borderRadius: 12,
    padding: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  collaboratorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primaryGradientMid,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  collaboratorAvatarText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  emptyOrgState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyOrgText: {
    fontSize: 14,
    color: colors.placeholder,
    textAlign: "center",
    marginBottom: 16,
  },
  createTeamCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1.5,
    borderColor: colors.primarySelectedBg,
  },
  createTeamIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  createTeamTitle: { fontSize: 14, fontWeight: "700", color: colors.dark },
  createTeamSub: { fontSize: 11, color: colors.placeholder, marginTop: 2 },
  collaboratorInfo: {
    flex: 1,
  },
  collaboratorName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.dark,
  },
  collaboratorUsername: {
    fontSize: 11,
    color: colors.placeholder,
    marginTop: 2,
  },

  // Pending approval banner
  pendingBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: colors.warningBg,
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    borderWidth: 1.5,
    borderColor: colors.warningBorder,
  },
  pendingBannerBody: { flex: 1 },
  pendingBannerTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.warningText,
    marginBottom: 3,
  },
  pendingBannerText: {
    fontSize: 12,
    color: colors.warningText,
    lineHeight: 17,
  },
  changePasswordBtn: {
    marginHorizontal: 16,
    borderRadius: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  changePasswordText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.primary,
    marginRight: 6,
  },
});
